# Generated by Django 4.1.7 on 2023-03-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_metriclistpage_metricpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricpage',
            name='intro',
        ),
    ]
