# Generated by Django 4.1.7 on 2023-03-24 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_metricpage_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='avg_reaction_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='avg_solve_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=24300), null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='num_created_last_week',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='num_solved_last_week',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='num_unsolved_now',
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='solved_last_week_ratio',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
