# Generated by Django 4.1.7 on 2023-03-27 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_metric_avg_reaction_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metric',
            old_name='num_unsolved_now',
            new_name='num_unsolved_week_start',
        ),
        migrations.AddField(
            model_name='metric',
            name='unsolved_last_week_start',
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='avg_solve_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 27, 20, 58, 11, 571985)),
        ),
    ]
