# Generated by Django 4.1.7 on 2023-03-27 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_num_unsolved_now_metric_num_unsolved_week_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='avg_reaction_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='Среднее время реакции на задачу на прошлой неделе'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='avg_solve_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='Среднее время решения задачи на прошлой неделе'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 27, 23, 46, 15, 458091), verbose_name='Дата формирования отчета:'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='num_created_last_week',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Создано на прошлой неделе'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='num_solved_last_week',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Решено на прошлой неделе'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='num_unsolved_week_start',
            field=models.IntegerField(blank=True, default=12, null=True, verbose_name='Не решено на начало текущей недели'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='solved_last_week_ratio',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Процент решенных проблем за прошлую неделю от общего числа нерешенных на начало прошлой недели'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='unsolved_last_week_start',
            field=models.IntegerField(blank=True, default=12, null=True, verbose_name='Не решено на начало прошлой недели'),
        ),
    ]
